export const WARNING = 'WARNING';
export const LOGIN_SACCEED = 'LOGIN_SACCEED';
export const LOGOUT = 'LOGOUT';

export const REGISTRATION_COMPLETED = 'REGISTRATION_COMPLETED';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

export const CALLS_LOADED = "CALLS_LOADED";
export const INFO_LOADED = "INFO_LOADED";
export const CALL_SUBMITTED = "CALL_SUBMITTED";
export const SEARCH_COMPLETED = "SEARCH_COMPLETED";

export const CALL_CREATED = "CALL_CREATED";

export const USER_CREATED ="USER_CREATED";

export const STATS_LOADED = "STATS_LOADED";
export const USER_INFO_LOADED = "USER_INFO_LOADED";
